extends:
  - 'eslint:recommended'
  - 'prettier'
plugins:
  - prettier
rules:
  no-empty:
    - error
    - allowEmptyCatch: true
  linebreak-style:
    - error
    - unix
  'prettier/prettier':
    - error